spring:
  profiles:
    active: development
  jpa:
    open-in-view: false
    properties:
      hibernate:
        envers:
          default_schema: aud
          revision_field_name: revision_number
          revision_type_field_name: revision_type
