INSERT INTO "INSURANCE_COMPANY" ("ID",
                                 "TAXPAYER_IDENTIFICATION_NUMBER",
                                 "PRIMARY_STATE_REGISTRATION_NUMBER",
                                 "FULL_NAME",
                                 "ADDRESS")
VALUES (1,
        '1111111111',
        '1111111111111',
        'Общество с ограниченной ответственностью Example Test',
        'Россия, Томская Область, город Томск, проспект Ленина, дом 1001, квартира 10001'),
       (2,
        '2222222222',
        '2222222222222',
        'Общество с ограниченной ответственностью New Example Test',
        'Россия, Томская Область, город Томск, Иркутский тракт, дом 505, квартира 50005'),
       (3,
        '3333333333',
        '3333333333333',
        'Общество с ограниченной ответственностью Third Example Test',
        'Россия, Томская Область, город Томск, Московский тракт, дом 999, квартира 9090');
SELECT SETVAL('insurance_company_id_seq', (SELECT MAX("ID") FROM "INSURANCE_COMPANY"))
